services:
  - type: web
    name: kinderpay
    env: docker
    region: frankfurt # choose your preferred region
    plan: free
    dockerfilePath: ./Dockerfile
    dockerCommand: "" # Uses ENTRYPOINT from Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: APP_KEY
        value: base64:bsTZLkU7jUQ+jYxbm2TlQEcPejpNHwvaPyR0q4RLRrc=
      - key: APP_URL
        value: https://kinderpay.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: SEED_ON_DEPLOY
        value: "false"
